---
- hosts: localhost
  gather_facts: false
  vars:
    nsxlicensekey: "{{ lookup('file', '{{ nsxlicense }}') }}"
  vars_files:
    - ../answerfile.yml
  tasks:

    - name: Add NSX-T license
      nsxt_licenses:
        hostname: "{{ nsxman.nsxman01.ip }}"
        username: "{{ nsxmanadminuser }}"
        password: "{{ nsxmanpassword }}"
        validate_certs: False
        license_key: "{{ nsxlicensekey }}"
        state: "present"
      when: 
        - deploy_nsxt == true
