---
- hosts: localhost
  gather_facts: false
  vars_files:
    - ../answerfile.yml
  tasks:
    - name: Check if NSX-T license file exists
      stat: 
        path: "{{ nsxlicense }}"
      register: nsxlicensekey

    - name: Load variables for NSX-T
      include_vars:
        file: nsxt_vars.yml
      when: 
        - nsxlicensekey.stat.exists == True        
        - deploy_nsxt == true
      
    - name: Attach NSX-T transport node profile to vSphere cluster
      nsxt_transport_node_collections:
        hostname: "{{ nsxman.nsxman01.ip }}"
        username: "{{ nsxmanadminuser }}"
        password: "{{ nsxmanpassword }}"
        validate_certs: False
        display_name: "TNC"
        resource_type: "TransportNodeCollection"
        description: "Transport Node Collections"
        compute_manager_name: "{{ vcenter.fqdn }}"
        cluster_name: "{{ item.key }}"
        transport_node_profile_name: "{{ tn_profile_name }}"
        state: present
      with_dict: "{{ clusters }}"
      when: 
        - nsxlicensekey.stat.exists == True
        - deploy_nsxt == true
        - item.value.prep_nsx == true
