---
- hosts: localhost
  gather_facts: false
  vars_files:
    - ../answerfile.yml
  tasks:
    - name: Load variables for NSX-T
      include_vars:
        file: nsxt_vars.yml
      when: deploy_nsxt == true

    - name: Create NSX-T 2.5 uplink profiles
      nsxt_uplink_profiles:
        hostname: "{{ nsxman.nsxman01.ip }}"
        username: "{{ nsxmanadminuser }}"
        password: "{{ nsxmanpassword }}"
        validate_certs: False
        resource_type: UplinkHostSwitchProfile
        display_name: "{{ item.display_name }}"
        teaming: "{{ item.teaming }}"
        transport_vlan: "{{ pod + transport }}" 
        state: "present"
      with_items:
        - "{{ uplink_profiles2 }}"
      when:
        - deploy_nsxt == true
        - nsxt_major_version == 2

    - name: Create NSX-T 3.0 uplink profiles
      nsxt_uplink_profiles:
        hostname: "{{ nsxman.nsxman01.ip }}"
        username: "{{ nsxmanadminuser }}"
        password: "{{ nsxmanpassword }}"
        validate_certs: False
        resource_type: UplinkHostSwitchProfile
        display_name: "{{ item.display_name }}"
        teaming: "{{ item.teaming }}"
        transport_vlan: "{{ pod + transport }}" 
        state: "present"
      with_items:
        - "{{ uplink_profiles3 }}"
      when:
        - deploy_nsxt == true
        - nsxt_major_version == 3