---
- hosts: localhost
  gather_facts: false
  vars_files:
    - ../answerfile.yml
  tasks:
    - name: Load variables for NSX-T
      include_vars:
        file: nsxt_vars.yml
      when: deploy_nsxt == true

    - name: Create NSX-T IP pool
      nsxt_ip_pools:
        hostname: "{{ nsxman.nsxman01.ip }}"
        username: "{{ nsxmanadminuser }}"
        password: "{{ nsxmanpassword }}"
        validate_certs: False
        display_name: "{{ item.display_name }}"
        subnets: "{{ item.subnets }}"
        state: present
      with_items:
        - "{{ ip_pools }}"
      when:
        - deploy_nsxt == true
