---
- hosts: localhost
  gather_facts: false
  vars_files:
    - ../answerfile.yml
  tasks:
    - name: Check if NSX-T manager is already installed
      uri:
        url: https://{{ item.value.ip }}
        validate_certs: False
        timeout: 5
      with_dict: "{{ nsxman }}"
      register: nsxman_check
      ignore_errors: true
      failed_when: false
      no_log: true
      when: deploy_nsxt == true

    - name: Deploy NSX-T Manager node from OVA
      vmware_deploy_ovf:
        hostname: "{{ physicalESX.fqdn }}"
        username: "{{ physicalESX.user }}"
        password: "{{ physicalESX.password }}"
        validate_certs: no
        datastore: "{{ physicalESX.datastore }}"
        name: "{{ item.item.value.vmname }}"
        ovf: "{{ NsxManOva }}"
        deployment_option: "{{ nsxmansize }}"
        networks:
          "Network 1": "{{ physicalESX.vlanpg }}"
        disk_provisioning: thin
        power_on: yes
        fail_on_spec_warnings: yes
        wait: yes
        wait_for_ip_address: yes
        inject_ovf_env: yes
        properties:
          nsx_allowSSHRootLogin: yes
          nsx_cli_audit_passwd_0: "{{ nsxmanpassword }}"
          nsx_cli_audit_username: "{{ nsxmanaudituser }}"
          nsx_cli_passwd_0: "{{ nsxmanpassword }}"
          nsx_cli_username: "{{ nsxmanadminuser }}"
          nsx_dns1_0: "{{ dns1 }}"
          nsx_domain_0: "{{ domain }}"
          nsx_gateway_0: "{{ pod_network }}.{{ pod + management }}.1"
          nsx_hostname: "{{ item.item.value.hostname }}"
          nsx_ip_0: "{{ item.item.value.ip }}"
          nsx_isSSHEnabled: True
          nsx_netmask_0: "{{ mgmt_network_mask }}"
          nsx_ntp_0: "{{ ntp1 }}"
          nsx_passwd_0: "{{ nsxmanpassword }}"
          nsx_role: "{{ nsxmanrole }}"
      delegate_to: localhost
      with_items: "{{ nsxman_check.results }}"
      when:
        - deploy_nsxt == true
        - item.status != 200
      async: 7200
      poll: 0
      register: deployment

    - name: Wait 3 seconds before start checking whether the NSX-T Manager node is ready
      pause: seconds=3
      when: 
        - deploy_nsxt == true
        - deployment.changed == true

    - name: Result check for NSX-T Manager node deployment
      async_status:
        jid: "{{ item.ansible_job_id }}"
      register: job_result
      with_items: "{{ deployment.results }}"
      when:
        - deploy_nsxt == true
        - deployment.changed == true
        - item.started is defined

    - name: Wait until the NSX-T API reports that the manager cluster is "STABLE" (wait max 60 minutes)
      uri:
        url: https://{{ item.value.ip }}/api/v1/cluster/status
        validate_certs: no
        timeout: 5
        force_basic_auth: yes
        url_username: "{{ nsxmanadminuser }}"
        url_password: "{{ nsxmanpassword }}"
        method: GET
        body_format: json
        return_content: yes
        status_code: 200
      with_dict: "{{ nsxman }}"
      register: result
      until: result.status == 200 and result.json.detailed_cluster_status.overall_status == "STABLE"
      retries: 120
      delay: 30
      when: 
        - deploy_nsxt == true
