---
- hosts: localhost
  gather_facts: false
  vars_files:
    - ./answerfile.yml
  tasks:

    - name: Remove VyOS router VM
      vmware_guest:
        hostname: "{{ physicalESX.fqdn }}"
        username: "{{ physicalESX.user }}"
        password: "{{ physicalESX.password }}"
        validate_certs: no
        name: "{{ router_vmname }}"
        force: true
        state: absent
      ignore_errors: true

    - name: Remove ESXi VMs
      vmware_guest:
        hostname: "{{ physicalESX.fqdn }}"
        username: "{{ physicalESX.user }}"
        password: "{{ physicalESX.password }}"
        validate_certs: no
        name: "{{ item.value.vmname }}"
        force: true
        state: absent
      async: 7200
      poll: 0     
      with_dict: "{{ vESX }}"
      ignore_errors: true

    - name: Remove vCenter VM
      vmware_guest:
        hostname: "{{ physicalESX.fqdn }}"
        username: "{{ physicalESX.user }}"
        password: "{{ physicalESX.password }}"
        validate_certs: no
        name: "{{ vcenter.vmname }}"
        force: true
        state: absent
      ignore_errors: true

    - name: Remove NSX Manager VM(s)
      vmware_guest:
        hostname: "{{ physicalESX.fqdn }}"
        username: "{{ physicalESX.user }}"
        password: "{{ physicalESX.password }}"
        validate_certs: no
        name: "{{ item.value.vmname }}"
        force: true
        state: absent
      async: 7200
      poll: 0        
      with_dict: "{{ nsxman }}"
      ignore_errors: true

    - name: Remove trunk port group for the nested environment
      vmware_portgroup:
        hostname: "{{ physicalESX.fqdn }}"
        username: "{{ physicalESX.user }}"
        password: "{{ physicalESX.password }}"
        validate_certs: False
        esxi_hostname: "{{ physicalESX.fqdn }}"
        switch_name: "{{ physicalESX.vswitch }}"
        portgroup_name: "{{ physicalESX.trunkpg }}"
        state: absent
      ignore_errors: true

    - name: Remove management port group for the nested environment
      vmware_portgroup:
        hostname: "{{ physicalESX.fqdn }}"
        username: "{{ physicalESX.user }}"
        password: "{{ physicalESX.password }}"
        validate_certs: False        
        esxi_hostname: "{{ physicalESX.fqdn }}"
        switch_name: "{{ physicalESX.vswitch }}"
        portgroup_name: "{{ physicalESX.vlanpg }}"
        state: absent
      ignore_errors: true

    - name: Remove VMware vSwitch on the ESXi host for the nested environment
      vmware_vswitch:
        hostname: "{{ physicalESX.fqdn }}"
        username: "{{ physicalESX.user }}"
        password: "{{ physicalESX.password }}"
        validate_certs: False
        esxi_hostname: "{{ physicalESX.fqdn }}"
        switch_name: "{{ physicalESX.vswitch }}"
        state: absent
      async: 7200
      poll: 0
      ignore_errors: true

    - name: Remove static route on the Ansible control node
      command: ./ip route del "{{ pod_network }}.{{ pod + management }}.0/24"
      args:
        chdir: /bin/
      register: iproute
      ignore_errors: true
      when: 
        - deploy_router == true
        - router.protocol == "static"

    - name: Delete the Pod documentation
      file: 
        path: "/home/$SUDO_USER/pod-{{ pod }}-doc.html"
        state: absent
      when: 
        - DEBUG_keep_config_files != true

